USE [master]
GO

/****** Object:  Database [essence-estapar]    Script Date: 07/11/2019 02:41:56 ******/
CREATE DATABASE [essence-estapar]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'essence-estapar', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\essence-estapar.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'essence-estapar_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\essence-estapar_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [essence-estapar].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [essence-estapar] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [essence-estapar] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [essence-estapar] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [essence-estapar] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [essence-estapar] SET ARITHABORT OFF 
GO

ALTER DATABASE [essence-estapar] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [essence-estapar] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [essence-estapar] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [essence-estapar] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [essence-estapar] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [essence-estapar] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [essence-estapar] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [essence-estapar] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [essence-estapar] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [essence-estapar] SET  DISABLE_BROKER 
GO

ALTER DATABASE [essence-estapar] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [essence-estapar] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [essence-estapar] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [essence-estapar] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [essence-estapar] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [essence-estapar] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [essence-estapar] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [essence-estapar] SET RECOVERY FULL 
GO

ALTER DATABASE [essence-estapar] SET  MULTI_USER 
GO

ALTER DATABASE [essence-estapar] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [essence-estapar] SET DB_CHAINING OFF 
GO

ALTER DATABASE [essence-estapar] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [essence-estapar] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [essence-estapar] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [essence-estapar] SET QUERY_STORE = OFF
GO

ALTER DATABASE [essence-estapar] SET  READ_WRITE 
GO

